### PR TITLE
Test with intern

### PR DESCRIPTION
**Pull request by mightyiam**

### CODE REVIEW

**Comment by dfguo** [comment]
Hi, I was looking for browserify and intern integration and found this stackoverflow comment: http://stackoverflow.com/questions/21853674/cant-load-modules-for-intern-testing-while-using-browserify

It looks like you guys no longer use intern to test. I'm just curious to know why since I'm in the middle of researching a testing solution. Thank you!

**Comment by mightyiam** [comment]
@dfguo Intern does not support commonjs modules and last time I checked not ES2015 modules.

This hack https://github.com/PolicyStat/edited/commit/c10e1a42a221b32148c3f75167e701c50a9a7615 is what I used to get a browserified module to work with intern. It is very dirty to me. I don't like AMD.

**Comment by mightyiam** [comment]
Next time I'll need to test something with selenium, I'll not use Intern. Nightwatch seems more like what I'd use but it is opinionated.

**Comment by dfguo** [comment]
hi @mightyiam, that's what I found too... I'm struggling a lot getting my webpack compiled modules work with Intern. I'm leaning towards Nightwatch now as well. Thank you for letting me know.

**Pull request merged**
